#!/usr/bin/env npx ts-node
/**
 * Generate TypeScript types from the backend OpenAPI spec.
 *
 * Usage:
 *   npm run generate-types
 *   npm run generate-types -- --url http://localhost:8010/openapi.json
 */

import openapiTS, { astToString } from 'openapi-typescript';
import * as fs from 'fs';
import * as path from 'path';

const DEFAULT_OPENAPI_URL = 'http://localhost:8000/openapi.json';
const OUTPUT_FILE = path.join(__dirname, '../src/lib/api-types.ts');

async function generateTypes(): Promise<void> {
  const args = process.argv.slice(2);
  let openApiUrl = DEFAULT_OPENAPI_URL;
  const urlIndex = args.indexOf('--url');
  if (urlIndex !== -1 && args[urlIndex + 1]) {
    openApiUrl = args[urlIndex + 1];
  }

  console.log(`📡 Generating types from: ${openApiUrl}`);

  try {
    // defaultNonNullable: false → a schema property is only emitted as required
    // when it is in the OpenAPI `required` array. Without this, v7 marks fields
    // that merely have a default (target_count, force_regenerate,
    // skip_llm_validation) as required, breaking ergonomic generate() callers.
    const ast = await openapiTS(new URL(openApiUrl), { defaultNonNullable: false });
    const contents = astToString(ast);

    const header = `/**
 * This file is auto-generated from the backend OpenAPI spec.
 * Do not edit this file manually.
 *
 * To regenerate, run: npm run generate-types
 * (make sure the backend is running first)
 *
 * Generated from: ${openApiUrl}
 */

`;
    fs.writeFileSync(OUTPUT_FILE, header + contents);
    console.log('✅ Types generated successfully!');
  } catch (error) {
    console.error('❌ Failed to generate types:', error);
    process.exit(1);
  }
}

generateTypes();
