#!/usr/bin/env npx ts-node
/**
 * Script to generate TypeScript types from the backend OpenAPI spec.
 * 
 * Usage:
 *   npm run generate-types
 *   npm run generate-types -- --url http://localhost:8000/openapi.json
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import * as fs from 'fs';
import * as path from 'path';

const execAsync = promisify(exec);

const DEFAULT_OPENAPI_URL = 'http://localhost:8000/openapi.json';
const OUTPUT_FILE = path.join(__dirname, '../src/lib/api-types.ts');

async function checkBackendAvailable(url: string): Promise<boolean> {
  try {
    const response = await fetch(url);
    return response.ok;
  } catch {
    return false;
  }
}

async function generateTypes(): Promise<void> {
  // Parse command line args for custom URL
  const args = process.argv.slice(2);
  let openApiUrl = DEFAULT_OPENAPI_URL;
  
  const urlIndex = args.indexOf('--url');
  if (urlIndex !== -1 && args[urlIndex + 1]) {
    openApiUrl = args[urlIndex + 1];
  }

  console.log(`📡 Fetching OpenAPI spec from: ${openApiUrl}`);

  // Check if backend is available
  const isAvailable = await checkBackendAvailable(openApiUrl);
  if (!isAvailable) {
    console.error('❌ Backend is not available. Please ensure the backend is running.');
    console.error(`   Expected OpenAPI spec at: ${openApiUrl}`);
    console.error('');
    console.error('   Start the backend with:');
    console.error('     cd backend && uvicorn main:app --reload');
    process.exit(1);
  }

  console.log('✅ Backend is available');
  console.log(`📝 Generating types to: ${OUTPUT_FILE}`);

  try {
    // Run openapi-typescript
    const { stdout, stderr } = await execAsync(
      `npx openapi-typescript "${openApiUrl}" -o "${OUTPUT_FILE}"`
    );

    if (stdout) console.log(stdout);
    if (stderr) console.error(stderr);

    // Add header comment to generated file
    const generatedContent = fs.readFileSync(OUTPUT_FILE, 'utf-8');
    const headerComment = `/**
 * This file is auto-generated from the backend OpenAPI spec.
 * Do not edit this file manually.
 * 
 * To regenerate, run: npm run generate-types
 * Make sure the backend is running first.
 * 
 * Generated from: ${openApiUrl}
 * Generated at: ${new Date().toISOString()}
 */

`;
    fs.writeFileSync(OUTPUT_FILE, headerComment + generatedContent);

    console.log('✅ Types generated successfully!');
    console.log('');
    console.log('📌 Usage:');
    console.log("   import type { components, paths } from '@/lib/api-types';");
    console.log('');
    console.log('   // Access schema types:');
    console.log("   type Feature = components['schemas']['FeatureRead'];");
    console.log("   type TestCase = components['schemas']['TestCaseRead'];");

  } catch (error) {
    console.error('❌ Failed to generate types:', error);
    process.exit(1);
  }
}

generateTypes();




