/**
 * This file is auto-generated from the backend OpenAPI spec.
 * Do not edit this file manually.
 *
 * To regenerate, run: npm run generate-types
 * (make sure the backend is running first)
 *
 * Generated from: http://localhost:8010/openapi.json
 */

export interface paths {
    "/api/v1/features/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Features
         * @description List all features with pagination (stable order by id).
         */
        get: operations["list_features_api_v1_features__get"];
        put?: never;
        /**
         * Create Feature
         * @description Create a new feature.
         */
        post: operations["create_feature_api_v1_features__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature
         * @description Get a specific feature by ID.
         */
        get: operations["get_feature_api_v1_features__feature_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Feature
         * @description Delete a feature and everything that references it.
         */
        delete: operations["delete_feature_api_v1_features__feature_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Feature
         * @description Update a feature.
         */
        patch: operations["update_feature_api_v1_features__feature_id__patch"];
        trace?: never;
    };
    "/api/v1/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List all templates with pagination.
         */
        get: operations["list_templates_api_v1_templates__get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new template.
         */
        post: operations["create_template_api_v1_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get a specific template by ID.
         */
        get: operations["get_template_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Delete a template.
         */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Template
         * @description Update a template.
         */
        patch: operations["update_template_api_v1_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Test Cases
         * @description Generate test cases for a feature using AI.
         *
         *     Uses the LLM service (with instructor) to generate structured test cases
         *     from the feature's requirements. Optionally uses a template for custom
         *     system instructions.
         *
         *     If the feature has linked features or test cases, their context is included
         *     in the LLM prompt for more informed test case generation.
         */
        post: operations["generate_test_cases_api_v1_generate__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate/feature/{feature_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Test Cases
         * @description Get all test cases for a specific feature.
         *
         *     Supports filtering by:
         *     - **status**: Filter by status (draft, accepted, rejected)
         *     - **is_edge_case**: Filter by edge case flag (true/false)
         *     - **is_manual**: Filter by manual flag (true/false)
         *     - **search**: Search by title (case-insensitive contains)
         */
        get: operations["get_feature_test_cases_api_v1_generate_feature__feature_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Test Case
         * @description Create a new test case (for manual entry).
         */
        post: operations["create_test_case_api_v1_test_cases__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Case
         * @description Get a specific test case by ID.
         */
        get: operations["get_test_case_api_v1_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Test Case
         * @description Delete a test case.
         */
        delete: operations["delete_test_case_api_v1_test_cases__test_case_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Test Case
         * @description Update a test case.
         */
        patch: operations["update_test_case_api_v1_test_cases__test_case_id__patch"];
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Test Case
         * @description Accept a test case (shortcut for status update).
         */
        post: operations["accept_test_case_api_v1_test_cases__test_case_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Test Case
         * @description Reject a test case (shortcut for status update).
         */
        post: operations["reject_test_case_api_v1_test_cases__test_case_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Test Case
         * @description Reset a test case to draft status.
         */
        post: operations["reset_test_case_api_v1_test_cases__test_case_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Status
         * @description Update status for multiple test cases at once.
         */
        post: operations["bulk_update_status_api_v1_test_cases_bulk_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine Test Suite
         * @description Refine the test suite for a feature.
         *
         *     This endpoint:
         *     1. Fetches all accepted and manual test cases for the feature
         *     2. Fetches linked context from related features and test cases
         *     3. Sends them to the LLM along with the original requirements
         *     4. The LLM performs gap analysis and generates new edge cases
         *     5. New cases are saved to the database with is_edge_case=True
         *     6. Returns the complete refined test suite
         */
        post: operations["refine_test_suite_api_v1_features__feature_id__refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Stats
         * @description Get statistics for a feature's test cases.
         */
        get: operations["get_feature_stats_api_v1_features__feature_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Test Cases
         * @description Export test cases for a feature.
         *
         *     Supports JSON and CSV formats. Optionally filter by status (draft, accepted, rejected).
         *
         *     - **feature_id**: ID of the feature to export test cases from
         *     - **format**: Export format - json or csv (default: json)
         *     - **status**: Optional filter by test case status
         */
        get: operations["export_test_cases_api_v1_features__feature_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/links": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Links
         * @description Get all links for a feature.
         *
         *     Returns both feature-to-feature and feature-to-test-case links.
         */
        get: operations["get_feature_links_api_v1_features__feature_id__links_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/links/feature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Feature Link
         * @description Create a feature-to-feature link.
         *
         *     Creates a bidirectional relationship between two features.
         *     The link type determines the relationship direction:
         *     - RELATES_TO: symmetric (A relates to B = B relates to A)
         *     - DEPENDS_ON: A depends on B = B blocks A
         *     - PARENT_OF: A is parent of B = B is child of A
         */
        post: operations["create_feature_link_api_v1_features__feature_id__links_feature_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/links/feature/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Feature Link
         * @description Delete a feature-to-feature link.
         *
         *     Also deletes the inverse link to maintain bidirectional consistency.
         */
        delete: operations["delete_feature_link_api_v1_features__feature_id__links_feature__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/links/test-case": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Test Case Link
         * @description Create a feature-to-test-case link.
         *
         *     Links a feature to a test case from another feature for context.
         *     The test case must belong to a different feature.
         */
        post: operations["create_test_case_link_api_v1_features__feature_id__links_test_case_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/links/test-case/{link_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Test Case Link
         * @description Delete a feature-to-test-case link.
         */
        delete: operations["delete_test_case_link_api_v1_features__feature_id__links_test_case__link_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - API health check.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BulkStatusUpdate
         * @description Schema for bulk status updates.
         */
        BulkStatusUpdate: {
            /** Test Case Ids */
            test_case_ids: number[];
            status: components["schemas"]["TestCaseStatus"];
        };
        /**
         * ExportFormat
         * @description Supported export formats.
         * @enum {string}
         */
        ExportFormat: "json" | "csv";
        /**
         * FeatureCreate
         * @description Schema for creating a Feature.
         */
        FeatureCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements: string;
            /**
             * Skip Llm Validation
             * @default false
             */
            skip_llm_validation?: boolean;
        };
        /**
         * FeatureLinkCreate
         * @description Schema for creating a feature link.
         */
        FeatureLinkCreate: {
            /** Target Feature Id */
            target_feature_id: number;
            link_type: components["schemas"]["FeatureLinkType"];
            /** Notes */
            notes?: string | null;
        };
        /**
         * FeatureLinkRead
         * @description Schema for reading a feature link.
         */
        FeatureLinkRead: {
            /** Id */
            id: number;
            /** Source Feature Id */
            source_feature_id: number;
            /** Target Feature Id */
            target_feature_id: number;
            link_type: components["schemas"]["FeatureLinkType"];
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Target Feature Title */
            target_feature_title?: string | null;
        };
        /**
         * FeatureLinkType
         * @description Type of relationship between features.
         * @enum {string}
         */
        FeatureLinkType: "relates_to" | "depends_on" | "blocks" | "parent_of" | "child_of";
        /**
         * FeatureLinksResponse
         * @description Response containing all links for a feature.
         */
        FeatureLinksResponse: {
            /** Feature Id */
            feature_id: number;
            /** Feature Links */
            feature_links: components["schemas"]["FeatureLinkRead"][];
            /** Test Case Links */
            test_case_links: components["schemas"]["TestCaseLinkRead"][];
        };
        /**
         * FeatureRead
         * @description Schema for reading a Feature.
         */
        FeatureRead: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generation Count
             * @default 0
             */
            generation_count?: number;
            /**
             * Refinement Count
             * @default 0
             */
            refinement_count?: number;
        };
        /**
         * FeatureUpdate
         * @description Schema for updating a Feature.
         */
        FeatureUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements?: string | null;
            /**
             * Skip Llm Validation
             * @default false
             */
            skip_llm_validation?: boolean;
        };
        /**
         * GenerateRequest
         * @description Request schema for test case generation.
         */
        GenerateRequest: {
            /** Feature Id */
            feature_id: number;
            /** Template Id */
            template_id?: number | null;
            /**
             * Skip Llm Validation
             * @default false
             */
            skip_llm_validation?: boolean;
            /**
             * Target Count
             * @default 10
             */
            target_count?: number;
            /**
             * Force Regenerate
             * @default false
             */
            force_regenerate?: boolean;
        };
        /**
         * GenerateResponse
         * @description Response schema for test case generation.
         */
        GenerateResponse: {
            /** Feature Id */
            feature_id: number;
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseDraft"][];
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RefinementRequest
         * @description Request schema for test suite refinement.
         */
        RefinementRequest: {
            /** Feature Id */
            feature_id: number;
            /** Template Id */
            template_id?: number | null;
            /**
             * Max New Cases
             * @default 5
             */
            max_new_cases?: number;
        };
        /**
         * RefinementResponse
         * @description Response schema for test suite refinement.
         */
        RefinementResponse: {
            /** Feature Id */
            feature_id: number;
            /** Original Count */
            original_count: number;
            /** New Count */
            new_count: number;
            /** Edge Cases Added */
            edge_cases_added: number;
            /**
             * Refinement Count
             * @default 0
             */
            refinement_count?: number;
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseRead"][];
            /** Message */
            message: string;
        };
        /**
         * TemplateCreate
         * @description Schema for creating a Template.
         */
        TemplateCreate: {
            /** Name */
            name: string;
            /** System Instructions */
            system_instructions: string;
        };
        /**
         * TemplateRead
         * @description Schema for reading a Template.
         */
        TemplateRead: {
            /** Name */
            name: string;
            /** System Instructions */
            system_instructions: string;
            /** Id */
            id: number;
        };
        /**
         * TemplateUpdate
         * @description Schema for updating a Template.
         */
        TemplateUpdate: {
            /** Name */
            name?: string | null;
            /** System Instructions */
            system_instructions?: string | null;
        };
        /**
         * TestCaseCreate
         * @description Schema for creating a TestCase.
         */
        TestCaseCreate: {
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /**
             * Is Edge Case
             * @default false
             */
            is_edge_case?: boolean;
            /**
             * Is Manual
             * @default false
             */
            is_manual?: boolean;
            /** Refinement Notes */
            refinement_notes?: string | null;
            /** @default draft */
            status?: components["schemas"]["TestCaseStatus"];
            /** Feature Id */
            feature_id: number;
        };
        /**
         * TestCaseDraft
         * @description Schema for LLM-generated test case drafts.
         */
        TestCaseDraft: {
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /**
             * Is Edge Case
             * @default false
             */
            is_edge_case?: boolean;
            /** Refinement Notes */
            refinement_notes?: string | null;
        };
        /**
         * TestCaseLinkCreate
         * @description Schema for creating a test case link.
         */
        TestCaseLinkCreate: {
            /** Test Case Id */
            test_case_id: number;
            /** Notes */
            notes?: string | null;
        };
        /**
         * TestCaseLinkRead
         * @description Schema for reading a test case link.
         */
        TestCaseLinkRead: {
            /** Id */
            id: number;
            /** Feature Id */
            feature_id: number;
            /** Test Case Id */
            test_case_id: number;
            /** Notes */
            notes: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Test Case Title */
            test_case_title?: string | null;
            /** Test Case Feature Id */
            test_case_feature_id?: number | null;
            /** Test Case Feature Title */
            test_case_feature_title?: string | null;
        };
        /**
         * TestCaseRead
         * @description Schema for reading a TestCase.
         */
        TestCaseRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /** Is Edge Case */
            is_edge_case: boolean;
            /** Is Manual */
            is_manual: boolean;
            /** Refinement Notes */
            refinement_notes: string | null;
            status: components["schemas"]["TestCaseStatus"];
            /** Feature Id */
            feature_id: number;
        };
        /**
         * TestCaseStatus
         * @description Status of a test case in the curation workflow.
         * @enum {string}
         */
        TestCaseStatus: "draft" | "accepted" | "rejected";
        /**
         * TestCaseUpdate
         * @description Schema for updating a TestCase.
         */
        TestCaseUpdate: {
            /** Title */
            title?: string | null;
            /** Steps */
            steps?: string[] | null;
            /** Expected Result */
            expected_result?: string | null;
            /** Is Edge Case */
            is_edge_case?: boolean | null;
            /** Is Manual */
            is_manual?: boolean | null;
            /** Refinement Notes */
            refinement_notes?: string | null;
            status?: components["schemas"]["TestCaseStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_features_api_v1_features__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feature_api_v1_features__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_api_v1_features__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feature_api_v1_features__feature_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feature_api_v1_features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_test_cases_api_v1_generate__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_test_cases_api_v1_generate_feature__feature_id__test_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TestCaseStatus"] | null;
                is_edge_case?: boolean | null;
                is_manual?: boolean | null;
                search?: string | null;
            };
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_case_api_v1_test_cases__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_case_api_v1_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_case_api_v1_test_cases__test_case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_case_api_v1_test_cases__test_case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_test_case_api_v1_test_cases__test_case_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_test_case_api_v1_test_cases__test_case_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_test_case_api_v1_test_cases__test_case_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_status_api_v1_test_cases_bulk_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_test_suite_api_v1_features__feature_id__refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefinementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefinementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_stats_api_v1_features__feature_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_test_cases_api_v1_features__feature_id__export_get: {
        parameters: {
            query?: {
                /** @description Export format (json or csv) */
                format?: components["schemas"]["ExportFormat"];
                /** @description Filter by status */
                status?: components["schemas"]["TestCaseStatus"] | null;
            };
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_links_api_v1_features__feature_id__links_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureLinksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feature_link_api_v1_features__feature_id__links_feature_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureLinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feature_link_api_v1_features__feature_id__links_feature__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_case_link_api_v1_features__feature_id__links_test_case_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseLinkCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseLinkRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_case_link_api_v1_features__feature_id__links_test_case__link_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
                link_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
