/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/features/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Features
         * @description List all features with pagination.
         */
        get: operations["list_features_api_v1_features__get"];
        put?: never;
        /**
         * Create Feature
         * @description Create a new feature.
         */
        post: operations["create_feature_api_v1_features__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature
         * @description Get a specific feature by ID.
         */
        get: operations["get_feature_api_v1_features__feature_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Feature
         * @description Delete a feature.
         */
        delete: operations["delete_feature_api_v1_features__feature_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Feature
         * @description Update a feature.
         */
        patch: operations["update_feature_api_v1_features__feature_id__patch"];
        trace?: never;
    };
    "/api/v1/templates/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Templates
         * @description List all templates with pagination.
         */
        get: operations["list_templates_api_v1_templates__get"];
        put?: never;
        /**
         * Create Template
         * @description Create a new template.
         */
        post: operations["create_template_api_v1_templates__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Template
         * @description Get a specific template by ID.
         */
        get: operations["get_template_api_v1_templates__template_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Template
         * @description Delete a template.
         */
        delete: operations["delete_template_api_v1_templates__template_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Template
         * @description Update a template.
         */
        patch: operations["update_template_api_v1_templates__template_id__patch"];
        trace?: never;
    };
    "/api/v1/generate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Test Cases
         * @description Generate test cases for a feature using AI.
         *
         *     Uses the LLM service (with instructor) to generate structured test cases
         *     from the feature's requirements. Optionally uses a template for custom
         *     system instructions.
         */
        post: operations["generate_test_cases_api_v1_generate__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/generate/feature/{feature_id}/test-cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Test Cases
         * @description Get all test cases for a specific feature.
         */
        get: operations["get_feature_test_cases_api_v1_generate_feature__feature_id__test_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Test Case
         * @description Create a new test case (for manual entry).
         */
        post: operations["create_test_case_api_v1_test_cases__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Case
         * @description Get a specific test case by ID.
         */
        get: operations["get_test_case_api_v1_test_cases__test_case_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Test Case
         * @description Delete a test case.
         */
        delete: operations["delete_test_case_api_v1_test_cases__test_case_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Test Case
         * @description Update a test case.
         */
        patch: operations["update_test_case_api_v1_test_cases__test_case_id__patch"];
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept Test Case
         * @description Accept a test case (shortcut for status update).
         */
        post: operations["accept_test_case_api_v1_test_cases__test_case_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Test Case
         * @description Reject a test case (shortcut for status update).
         */
        post: operations["reject_test_case_api_v1_test_cases__test_case_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/{test_case_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Test Case
         * @description Reset a test case to draft status.
         */
        post: operations["reset_test_case_api_v1_test_cases__test_case_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/test-cases/bulk-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Status
         * @description Update status for multiple test cases at once.
         */
        post: operations["bulk_update_status_api_v1_test_cases_bulk_status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine Test Suite
         * @description Refine the test suite for a feature.
         *
         *     This endpoint:
         *     1. Fetches all accepted and manual test cases for the feature
         *     2. Sends them to the LLM along with the original requirements
         *     3. The LLM performs gap analysis and generates new edge cases
         *     4. New cases are saved to the database with is_edge_case=True
         *     5. Returns the complete refined test suite
         */
        post: operations["refine_test_suite_api_v1_features__feature_id__refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features/{feature_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feature Stats
         * @description Get statistics for a feature's test cases.
         */
        get: operations["get_feature_stats_api_v1_features__feature_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint - API health check.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BulkStatusUpdate
         * @description Schema for bulk status updates.
         */
        BulkStatusUpdate: {
            /** Test Case Ids */
            test_case_ids: number[];
            status: components["schemas"]["TestCaseStatus"];
        };
        /**
         * FeatureCreate
         * @description Schema for creating a Feature.
         */
        FeatureCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements: string;
        };
        /**
         * FeatureRead
         * @description Schema for reading a Feature.
         */
        FeatureRead: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FeatureUpdate
         * @description Schema for updating a Feature.
         */
        FeatureUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Raw Requirements */
            raw_requirements?: string | null;
        };
        /**
         * GenerateRequest
         * @description Request schema for test case generation.
         */
        GenerateRequest: {
            /** Feature Id */
            feature_id: number;
            /** Template Id */
            template_id?: number | null;
        };
        /**
         * GenerateResponse
         * @description Response schema for test case generation.
         */
        GenerateResponse: {
            /** Feature Id */
            feature_id: number;
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseDraft"][];
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RefinementRequest
         * @description Request schema for test suite refinement.
         */
        RefinementRequest: {
            /** Feature Id */
            feature_id: number;
            /** Template Id */
            template_id?: number | null;
        };
        /**
         * RefinementResponse
         * @description Response schema for test suite refinement.
         */
        RefinementResponse: {
            /** Feature Id */
            feature_id: number;
            /** Original Count */
            original_count: number;
            /** New Count */
            new_count: number;
            /** Edge Cases Added */
            edge_cases_added: number;
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseRead"][];
            /** Message */
            message: string;
        };
        /**
         * TemplateCreate
         * @description Schema for creating a Template.
         */
        TemplateCreate: {
            /** Name */
            name: string;
            /** System Instructions */
            system_instructions: string;
        };
        /**
         * TemplateRead
         * @description Schema for reading a Template.
         */
        TemplateRead: {
            /** Name */
            name: string;
            /** System Instructions */
            system_instructions: string;
            /** Id */
            id: number;
        };
        /**
         * TemplateUpdate
         * @description Schema for updating a Template.
         */
        TemplateUpdate: {
            /** Name */
            name?: string | null;
            /** System Instructions */
            system_instructions?: string | null;
        };
        /**
         * TestCaseCreate
         * @description Schema for creating a TestCase.
         */
        TestCaseCreate: {
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /**
             * Is Edge Case
             * @default false
             */
            is_edge_case: boolean;
            /**
             * Is Manual
             * @default false
             */
            is_manual: boolean;
            /** Refinement Notes */
            refinement_notes?: string | null;
            /** @default draft */
            status: components["schemas"]["TestCaseStatus"];
            /** Feature Id */
            feature_id: number;
        };
        /**
         * TestCaseDraft
         * @description Schema for LLM-generated test case drafts.
         */
        TestCaseDraft: {
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /**
             * Is Edge Case
             * @default false
             */
            is_edge_case: boolean;
            /** Refinement Notes */
            refinement_notes?: string | null;
        };
        /**
         * TestCaseRead
         * @description Schema for reading a TestCase.
         */
        TestCaseRead: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /** Is Edge Case */
            is_edge_case: boolean;
            /** Is Manual */
            is_manual: boolean;
            /** Refinement Notes */
            refinement_notes: string | null;
            status: components["schemas"]["TestCaseStatus"];
            /** Feature Id */
            feature_id: number;
        };
        /**
         * TestCaseStatus
         * @description Status of a test case in the curation workflow.
         * @enum {string}
         */
        TestCaseStatus: "draft" | "accepted" | "rejected";
        /**
         * TestCaseUpdate
         * @description Schema for updating a TestCase.
         */
        TestCaseUpdate: {
            /** Title */
            title?: string | null;
            /** Steps */
            steps?: string[] | null;
            /** Expected Result */
            expected_result?: string | null;
            /** Is Edge Case */
            is_edge_case?: boolean | null;
            /** Is Manual */
            is_manual?: boolean | null;
            /** Refinement Notes */
            refinement_notes?: string | null;
            status?: components["schemas"]["TestCaseStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_features_api_v1_features__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feature_api_v1_features__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_api_v1_features__feature_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feature_api_v1_features__feature_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feature_api_v1_features__feature_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeatureUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_templates__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_template_api_v1_templates__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_template_api_v1_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_template_api_v1_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_template_api_v1_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_test_cases_api_v1_generate__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_test_cases_api_v1_generate_feature__feature_id__test_cases_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_case_api_v1_test_cases__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_case_api_v1_test_cases__test_case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_case_api_v1_test_cases__test_case_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_case_api_v1_test_cases__test_case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCaseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_test_case_api_v1_test_cases__test_case_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_test_case_api_v1_test_cases__test_case_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_test_case_api_v1_test_cases__test_case_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                test_case_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_status_api_v1_test_cases_bulk_status_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCaseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_test_suite_api_v1_features__feature_id__refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefinementRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefinementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feature_stats_api_v1_features__feature_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feature_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
